### ISSUE TITLE
64x branch is missing latest build fix

### ISSUE THREAD

**Issue by RaphaelIT7** [danielga/garrysmod_common#113]
Compiling currently fails because of the missing string include, which was fixed with https://github.com/danielga/garrysmod_common/commit/bff6eb3a44177307b71fa49000343d051c6087b9 but never applied to 64x

![image](https://github.com/user-attachments/assets/c9379eb1-d2c1-43b2-a0fc-4b45d2eb93c8)

**Comment by danielga** [comment]
I've rebased `x86-64-support-sourcesdk` onto `master`.
