### ISSUE TITLE
os.target() is apparently a nil value when trying to use premake5

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/garrysmod_common#45]
Currently trying to use premake5 on WSL with Ubuntu 16.04. when I run premake5 --os=linux gmake under the serversecure folder it runs into an issue with garrysmod_common

vaas_net@VAASNET:/mnt/c/linux_compiles/serversecure/gmsv_serversecure$ premake5 --os=linux gmake
Error: ...ecure/garrysmod_common/premake/config.v2.default.lua:4: attempt to call field 'target' (a nil value)

I have tried with and without the --os=linux in the command but the same issue occurs

**Comment by danielga** [comment]
Use [this version](https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz) of premake5 (available from [their website](https://premake.github.io/download.html)).

**Comment by VaasKahnGrim** [comment]
I did, I followed this tutorial right here for the same version of premake5 https://github.com/glua/module-base/wiki/Installing-Premake5

**Comment by VaasKahnGrim** [comment]
managed to fix it somehow, something apparently messed up when I first installed premake5. just reinstalled it and it worked
