### ISSUE TITLE
x64 Support and CMake

### ISSUE THREAD

**Issue by dhkatz** [danielga/garrysmod_common#46]
Is the x64 support support finished for this?

Also, it seems that [gmod-module-base](https://github.com/Facepunch/gmod-module-base/tree/development) has switched to CMake. Seeing as CMake is basically the defacto build tool for C++ (especially because of nice CMake is as of 3.13),.

Do you have any plans to switch this library to use CMake?

**Comment by danielga** [comment]
In regards to x86_64, if I remember correctly, it was only missing sourcesdk-minimal support.
About CMake, I don't see the point in changing to it, since it's, in my opinion, more convoluted than premake and I already do a lot of work to facilitate module creation with it.

**Comment by SupinePandora43** [comment]
@danielga can you say required thing for proper working `sourcesdk_minimal` with cmake?
after i defined `"COMPILER_MSVC64" "WIN32" "ARCHITECTURE_X86_64"`
and including `dbg.h` it causes many errors!

**Comment by danielga** [comment]
Easiest way would be to generate a project for one of my modules and getting the defines from it.

**Comment by dankmolot** [comment]
I have made cmake project files for garrysmod_common and its submodules for main and x86-64 beta branches, and I'm interested in maintaining since I use them in my last 4 projects. I can create pull requests to branches, or manage myself cmake branches while updating them with upstream. What do you think?

**Comment by dhkatz** [comment]
> I have made cmake project files for garrysmod_common and its submodules for main and x86-64 beta branches, and I'm interested in maintaining since I use them in my last 4 projects. I can create pull requests to branches, or manage myself cmake branches while updating them with upstream. What do you think?

I hope this can be done in some way. CMake is the defacto build tool for C++ now in 2023. Modern CMake is certainly nicer than whatever grievances there might have been in the past.

**Comment by dankmolot** [comment]
> I hope this can be done in some way. CMake is the defacto build tool for C++ now in 2023. Modern CMake is certainly nicer than whatever grievances there might have been in the past.

I already have it done in [my garrysmod_common repo](https://github.com/dankmolot/garrysmod_common/tree/master-cmake#usage-with-cmake). Also don't forget to change branch to `master-cmake` or `x86-64-cmake`. For example, you can look to [gm_moonloader](https://github.com/Pika-Software/gm_moonloader#compilation) as a cmake project reference.

**Comment by danielga** [comment]
> I have made cmake project files for garrysmod_common and its submodules for main and x86-64 beta branches, and I'm interested in maintaining since I use them in my last 4 projects. I can create pull requests to branches, or manage myself cmake branches while updating them with upstream. What do you think?

If you make a PR for that, I'll have a look eventually. I can't promise official support for it however (aka it'll be community maintained).
