### ISSUE TITLE
x86-64 issue, can't compile garrysmod_common cus of missing const Symbol net_sockets

### ISSUE THREAD

**Issue by Garrysman232** [danielga/garrysmod_common#56]
## x86-64 Issue
Case ```"#if defined ARCHITECTURE_X86_64"```  missing its
```C++
const Symbol net_sockets
```

https://github.com/danielga/garrysmod_common/blob/master/helpers_extended/source/Symbols.cpp#L54

**Comment by danielga** [comment]
Fixed in commit 51fc5f1316631c8e45094b81a3eea2a6bd690b7a
