### ISSUE TITLE
Remove lua_resume quirks

### ISSUE THREAD

**Issue by Cheatoid** [danielga/garrysmod_common#70]
Looking at the lua_shared export table, I found that you're defining non-existing `lua_resume` function,
which is actually named `lua_resume_real` (which you already defined).
In other words, remove [this line](https://github.com/danielga/garrysmod_common/blob/016889382defeca2e071af0d8948d5aa3a72e339/lua_shared/source/LuaShared.cpp#L255) and then also remove [this line](https://github.com/danielga/garrysmod_common/blob/016889382defeca2e071af0d8948d5aa3a72e339/include/lua.h#L216) too cuz it is not exported (and never was).

**Comment by danielga** [comment]
Done.
