### ISSUE TITLE
Catch up with the latest LuaJIT updates in GMod

### ISSUE THREAD

**Issue by Cheatoid** [danielga/garrysmod_common#71]
This is still on even older version of [LuaJIT 2.0.4](https://github.com/danielga/garrysmod_common/blob/016889382defeca2e071af0d8948d5aa3a72e339/include/luajit.h#L33), damn Daniel, this is outdated by two luashared updates...
(i don't remember the changes between 2.0.4 and 2.0.5, so you're on your own for updating that.)

The following is the set of changes I have noticed between LuaJIT 2.0.5 (previous luashared version) and LuaJIT 2.1.0-beta3 (current luashared version).
## ***tldr***
<details>
<summary><b><code>lauxlib.h</code></b> (click meee)</summary>

- Remove macros: `luaL_getn`, `luaL_setn`, `lua_ref`, `lua_unref`,`lua_getref` and `luaL_reg`
- Add functions (new exports): `luaL_setfuncs`, `luaL_pushmodule`, `luaL_testudata` and `luaL_setmetatable`
- Add macros: `luaL_newlibtable` and `luaL_newlib`

</details>

<details>
<summary><b><code>lua.h</code></b> (click meee)</summary>

- Add macro: `LUA_OK` (0) for thread status
- Add macro: `LUA_GCISRUNNING` (9) option for gc
- Add functions (new exports): `lua_version`, `lua_copy`, `lua_tonumberx`, `lua_tointegerx` and `lua_isyieldable`

</details>

<details>
<summary><b><code>luaconf.h</code></b> (click meee)</summary>

- Remove macros: LUA_COMPAT_MOD and LUA_COMPAT_GFIND

</details>

<details>
<summary><b><code>luajit.h</code></b> (click meee)</summary>

- Update macros: `LUAJIT_VERSION`, `LUAJIT_VERSION_NUM` and `LUAJIT_VERSION_SYM`
- Add typedef: `luaJIT_profile_callback`
- Add functions (new exports): `luaJIT_profile_start`, `luaJIT_profile_stop` and `luaJIT_profile_dumpstack`

</details>

**Comment by danielga** [comment]
Updated the x86-64 branch with LuaJIT 2.1.0-beta3 headers.
