### ISSUE TITLE
GModDataPack_AddOrUpdateFile outdated

### ISSUE THREAD

**Issue by notsleepily** [danielga/garrysmod_common#72]
dunno when it happened but a working sig is
`\x55\x8b\xec\x83\xec\x28\x53\x8b\x5d\x08\x83\x7b\x18\x10`

**Comment by danielga** [comment]
Thank you for the heads up. I confirmed the signature changed and updated it on 1963a85a5b53047dbf248df3ebb4ef29660147e3.
