### ISSUE TITLE
Mathlib cannot be built. Tried under 32 bit aswell

### ISSUE THREAD

**Issue by Synkstar** [danielga/garrysmod_common#75]
This is when using the x86-64 version I have tried including everything in the sourcesdk its only mathlib that doesnt work. 
`
==== Building mathlib (release_x86_64) ====
box_buoyancy.cpp
../../../mathlib/box_buoyancy.cpp:329:106: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
  329 | const int32 ALIGN16 g_SIMD_signmask_W[4] ALIGN16_POST = { 0x80000000, 0x80000000, 0x80000000, 0xFFFFFFFF };
      |                                                                                                          ^
../../../mathlib/box_buoyancy.cpp:329:106: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
../../../mathlib/box_buoyancy.cpp:329:106: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
../../../mathlib/box_buoyancy.cpp:329:106: error: narrowing conversion of ‘4294967295’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
../../../mathlib/box_buoyancy.cpp:330:99: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
  330 | const int32 ALIGN16 g_SIMD_signmask_NoW[4] ALIGN16_POST = { 0x80000000, 0x80000000, 0x80000000, 0 };
      |                                                                                                   ^
../../../mathlib/box_buoyancy.cpp:330:99: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
../../../mathlib/box_buoyancy.cpp:330:99: error: narrowing conversion of ‘2147483648’ from ‘unsigned int’ to ‘int32’ {aka ‘int’} [-Wnarrowing]
make[1]: *** [mathlib.make:257: x86_64/Release/intermediate/mathlib/box_buoyancy.o] Error 1
make: *** [Makefile:111: mathlib] Error 2
`
Im compiling it on ubuntu server 20.04

**Comment by danielga** [comment]
Should be fixed with the latest changes to the `x86-64-support-sourcesdk`. Will require a rebase since it's a WIP branch.
