### ISSUE TITLE
Invalid lua_State* from ILuaBase*

### ISSUE THREAD

**Issue by Asrielxz** [danielga/garrysmod_common#77]
Hi there, I was wondering if there was an issue with the internal state within the module? I'm trying to use some internal lua functions (i.e: lua_gettop) which I pass in the state from (LUA->GetState()) but the server instantly crashes when it's executed. I'm using the x64 branch along with the x64 github branch. Example code is below which will cause a crash:

```
GMOD_MODULE_OPEN()
{	
	std::cout << "lua_gettop = " << lua_gettop(LUA->GetState()) << std::endl;

	return 0;
}

```
Not sure if it's something I'm doing wrong or if there's an issue currently but feel free to correct me if I'm doing something wrong, thanks.

**Comment by danielga** [comment]
I'll need more information about your module, preferably a reproducible sample. I don't know how you're linking to Lua, for example.

**Comment by Asrielxz** [comment]
After some further debugging, it seems that it crashes on the menu state, but server state is fine.

This code can reproduce the problem:

```
#include <iostream>
#include <GarrysMod/Lua/Interface.h>
#include <lua.hpp>

GMOD_MODULE_OPEN()
{	
	std::cout << "lua_gettop = " << lua_gettop(LUA->GetState()) << std::endl;

	return 0;
}

GMOD_MODULE_CLOSE()
{
	return 0;
}
```

I'm trying to make a module that will communicate to the server as a project. Do you have any idea why the state would be non-functional on the menu? My server module seems to work fine now (it was crashing aswell before but seems to no longer crash) but the menu one crashes 100% of the time

**Comment by Asrielxz** [comment]
Is there any update on this? It's been 11 days with silence after providing a reproducible example.

**Comment by danielga** [comment]
Can't reproduce the crash. Windows, Garry's Mod x86-64 using the 64 bits binary, with exactly your code.

**Comment by Asrielxz** [comment]
Are you using ``x86-64-support-sourcesdk``? My game instantly crashes with that exact code and no other code at all, I'm using ``x86-64-support-sourcesdk`` along with the provided submodules and no dice.

**Comment by danielga** [comment]
Retried with that branch, same situation. I wasn't expecting it to fail anyway, since there's barely any differences between these two branches, besides the `sourcesdk-minimal` submodule.
