### ISSUE TITLE
'Symbols::Steam3Server': redefinition; different basic types

### ISSUE THREAD

**Issue by klen-list** [danielga/garrysmod_common#81]
Platform: Windows x64
Configuration: ReleaseWithSymbols
`Error (active) E0147 declaration is incompatible with "const Symbol Symbols::Steam3Server" (declared at line 72 of "..\garrysmod_common\helpers_extended\source\Symbols.cpp") helpers_extended ..\garrysmod_common\helpers_extended\include\GarrysMod\Symbols.hpp 25`

**Comment by danielga** [comment]
Should be fixed in 72f62b4bb2ee33e05bfbc3ea79e48ba54e952904.
