### ISSUE TITLE
How to compile my module for linux

### ISSUE THREAD

**Issue by Zekirax** [danielga/garrysmod_common#83]
Do you know which os can compile gmod module. Or a wsl ?

**Comment by Zekirax** [comment]
I have seen that I can upgrade my ubuntu but this is not my server. I can't upgrade the os.

**Comment by Zekirax** [comment]
Couldn't load module library! (/lib/i386-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

**Comment by danielga** [comment]
You need a slightly older glibc version. Usually, you can just get an older or the same version of the target OS (on WSL) and compile there.

**Comment by Zekirax** [comment]
My wsl :
Ubuntu GLIBC 2.31
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

I'll try trie to install Glibc 2.29.

**Comment by danielga** [comment]
What is the target OS?

**Comment by Zekirax** [comment]
For the moment the server is on this https://mtxserv.com/fr/serveur-gmod. I only know Linux x86. But I read that using an older version of ubuntu is a good way.

**Comment by Zekirax** [comment]
Do you know an OS and version with Glibc 2.29?

**Comment by FlorianLeChat** [comment]
MtxServ servers use Debian 10 iirc

**Comment by Zekirax** [comment]
Thanks @FlorianLeChat

**Comment by Zekirax** [comment]
worked for me :

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27

Thank you!
