### ISSUE TITLE
Exception thrown: read access violation. pointer was 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by URAKOLOUY5** [danielga/garrysmod_common#88]
Crash happens when I try to use `GlobalVars` from InterfacePointers.

![](https://media.discordapp.net/attachments/619231812987650059/1068242401463906364/image.png)

**Comment by danielga** [comment]
From the pointer address, I'm assuming you got this on the x86-64 branch. I've stopped supporting it, until Facepunch becomes serious and makes it official, no betas.
