### ISSUE TITLE
Attempt to call a nil value externalincludedirs

### ISSUE THREAD

**Issue by Be1zebub** [danielga/garrysmod_common#90]
Error: ...ents/gm_io_events/garrysmod_common/premake/generator.lua:340: attempt to call a nil value (global 'externalincludedirs')
revert https://github.com/danielga/garrysmod_common/commit/eec45c4375fb8dd3b5008a965a8f0e19796e873d or define externalincludedirs

**Comment by Be1zebub** [comment]
Error: ...p/garrysmod_common/sourcesdk-minimal/common/premake5.lua:9: attempt to call a nil value (global 'externalincludedirs') https://github.com/danielga/sourcesdk-minimal/commit/fd4f11e418e39c847e01821085b8c1b3df2ca387

**Comment by klen-list** [comment]
It seems that for a long time on the premake5 site in `Pre-Built Binaries` for Windows was only available `v5.0.0-beta1`, now it is `v5.0.0-beta2` in which externalincludedirs are present

**Comment by danielga** [comment]
beta2 has been available since September of last year. Anyway, I've added a version checking for the premake5 executable, so this should be more explicit.
