### ISSUE TITLE
GModDataPack AddOrUpdateFile Windows signature

### ISSUE THREAD

**Issue by dedrusss** [danielga/garrysmod_common#96]
Fix [this](https://github.com/danielga/garrysmod_common/blob/45ef7c7c2a86704bb2dfd72c96ced0359376ea30/helpers_extended/source/Symbols.cpp#L171) signature, [luapack](https://github.com/danielga/luapack) module dosent work on windows, after last gmod update.

![image](https://github.com/danielga/garrysmod_common/assets/13808068/9f144e6e-eb2f-429f-9fd5-83015b9df604)

**Comment by magnalunar** [comment]
A new pull request (368b477dbe97ad2c51746ba332f244da9ecb009b) is waiting for merge.

**Comment by notSeriosulyLolek** [comment]
hello, I'm getting the same error (can't use on windows)

**Comment by danielga** [comment]
Open a new issue please. This has been fixed
